-- Clears old data on restart so new columns (like difficulty) apply
DELETE FROM word;

INSERT INTO word (original, category, difficulty, hint1, hint2)
SELECT * FROM (VALUES
    -- ANIMALS (Original 13 + 87 new = 100)
    ROW('cat',        'Animals','EASY',  'A common pet',                    'Meows and purrs'),
    ROW('dog',        'Animals','EASY',  'Man''s best friend',              'Barks and wags tail'),
    ROW('bird',       'Animals','EASY',  'It has wings',                    'Lays eggs in a nest'),
    ROW('fish',       'Animals','EASY',  'Swims in water',                  'Has gills and scales'),
    ROW('bear',       'Animals','EASY',  'Large furry mammal',              'Likes honey'),
    ROW('lion',       'Animals','EASY',  'King of the jungle',              'Has a big mane'),
    ROW('tiger',      'Animals','EASY',  'Striped big cat',                 'Lives in Asia'),
    ROW('cow',        'Animals','EASY',  'Farm animal',                     'Gives us milk'),
    ROW('pig',        'Animals','EASY',  'Farm animal',                     'Rolls in mud'),
    ROW('horse',      'Animals','EASY',  'You can ride it',                 'Says neigh'),
    ROW('sheep',      'Animals','EASY',  'Woolly farm animal',              'Says baa'),
    ROW('goat',       'Animals','EASY',  'Farm animal with horns',          'Eats almost anything'),
    ROW('duck',       'Animals','EASY',  'Waterfowl',                       'Says quack'),
    ROW('frog',       'Animals','EASY',  'Amphibian',                       'Hops and ribbits'),
    ROW('snake',      'Animals','EASY',  'Legless reptile',                 'Some are venomous'),
    ROW('mouse',      'Animals','EASY',  'Small rodent',                    'Cats chase it'),
    ROW('rabbit',     'Animals','EASY',  'Has long ears',                   'Hops around'),
    ROW('wolf',       'Animals','EASY',  'Wild canine',                     'Howls at the moon'),
    ROW('fox',        'Animals','EASY',  'Cunning wild animal',             'Red fur typically'),
    ROW('deer',       'Animals','EASY',  'Forest animal',                   'Males have antlers'),
    ROW('monkey',     'Animals','EASY',  'Primate',                         'Swings from trees'),
    ROW('chicken',    'Animals','EASY',  'Farm bird',                       'Lays eggs we eat'),
    ROW('ant',        'Animals','EASY',  'Tiny insect',                     'Lives in colonies'),
    ROW('bee',        'Animals','EASY',  'Flying insect',                   'Makes honey'),
    ROW('spider',     'Animals','EASY',  'Eight-legged creature',           'Spins webs'),
    ROW('elephant',   'Animals','MEDIUM','Large mammal',                    'Has a trunk'),
    ROW('giraffe',    'Animals','MEDIUM','Tallest land animal',             'Has a very long neck'),
    ROW('penguin',    'Animals','MEDIUM','Flightless bird',                 'Lives in cold climates'),
    ROW('kangaroo',   'Animals','MEDIUM','Marsupial from Australia',        'Hops and has a pouch'),
    ROW('dolphin',    'Animals','MEDIUM','Smart sea mammal',                'Known for intelligence'),
    ROW('whale',      'Animals','MEDIUM','Largest animal',                  'Lives in the ocean'),
    ROW('shark',      'Animals','MEDIUM','Ocean predator',                  'Has many teeth'),
    ROW('octopus',    'Animals','MEDIUM','Eight-armed sea creature',        'Very intelligent'),
    ROW('turtle',     'Animals','MEDIUM','Has a shell',                     'Moves slowly'),
    ROW('crocodile',  'Animals','MEDIUM','Large reptile',                   'Lives in swamps'),
    ROW('parrot',     'Animals','MEDIUM','Colorful bird',                   'Can mimic speech'),
    ROW('owl',        'Animals','MEDIUM','Nocturnal bird',                  'Can rotate its head'),
    ROW('eagle',      'Animals','MEDIUM','Bird of prey',                    'Symbol of freedom'),
    ROW('zebra',      'Animals','MEDIUM','Striped horse-like animal',       'Black and white'),
    ROW('camel',      'Animals','MEDIUM','Desert animal',                   'Has humps'),
    ROW('gorilla',    'Animals','MEDIUM','Large ape',                       'Very strong'),
    ROW('chimpanzee', 'Animals','MEDIUM','Closest to humans',               'Uses tools'),
    ROW('leopard',    'Animals','MEDIUM','Spotted big cat',                 'Great climber'),
    ROW('jaguar',     'Animals','MEDIUM','South American big cat',          'Strongest bite'),
    ROW('panther',    'Animals','MEDIUM','Black big cat',                   'Stealthy hunter'),
    ROW('buffalo',    'Animals','MEDIUM','Large bovine',                    'Roams in herds'),
    ROW('moose',      'Animals','MEDIUM','Largest deer species',            'Huge antlers'),
    ROW('koala',      'Animals','MEDIUM','Australian marsupial',            'Eats eucalyptus'),
    ROW('sloth',      'Animals','MEDIUM','Very slow animal',                'Hangs from trees'),
    ROW('raccoon',    'Animals','MEDIUM','Masked animal',                   'Nocturnal scavenger'),
    ROW('squirrel',   'Animals','MEDIUM','Bushy-tailed rodent',             'Collects nuts'),
    ROW('beaver',     'Animals','MEDIUM','Builds dams',                     'Flat tail'),
    ROW('otter',      'Animals','MEDIUM','Playful water mammal',            'Floats on its back'),
    ROW('seal',       'Animals','MEDIUM','Marine mammal',                   'Barks like a dog'),
    ROW('walrus',     'Animals','MEDIUM','Arctic marine mammal',            'Has tusks'),
    ROW('panda',      'Animals','MEDIUM','Black and white bear',            'Eats bamboo'),
    ROW('flamingo',   'Animals','MEDIUM','Pink bird',                       'Stands on one leg'),
    ROW('peacock',    'Animals','MEDIUM','Bird with beautiful tail',        'Fans its feathers'),
    ROW('swan',       'Animals','MEDIUM','Elegant water bird',              'Long curved neck'),
    ROW('crab',       'Animals','MEDIUM','Has pincers',                     'Walks sideways'),
    ROW('lobster',    'Animals','MEDIUM','Seafood delicacy',                'Red when cooked'),
    ROW('jellyfish',  'Animals','MEDIUM','Transparent sea creature',        'Can sting'),
    ROW('starfish',   'Animals','MEDIUM','Star-shaped sea creature',        'Can regrow arms'),
    ROW('seahorse',   'Animals','MEDIUM','Fish shaped like a horse',        'Male carries babies'),
    ROW('butterfly',  'Animals','MEDIUM','Colorful flying insect',          'Starts as caterpillar'),
    ROW('dragonfly',  'Animals','MEDIUM','Fast flying insect',              'Lives near water'),
    ROW('hippopotamus','Animals','HARD', 'Large, mostly herbivorous mammal','Native to sub-Saharan Africa'),
    ROW('chameleon',  'Animals','HARD',  'Lizard known for changing color', 'Has highly stereoscopic eyes'),
    ROW('rhinoceros', 'Animals','HARD',  'Large thick-skinned herbivore',   'Has one or two horns on its snout'),
    ROW('platypus',   'Animals','HARD',  'Egg-laying mammal',               'Has a duck-like bill'),
    ROW('armadillo',  'Animals','HARD',  'Armored mammal',                  'Rolls into a ball'),
    ROW('anteater',   'Animals','HARD',  'Long-snouted mammal',             'Eats insects'),
    ROW('pangolin',   'Animals','HARD',  'Scaly mammal',                    'Most trafficked animal'),
    ROW('tapir',      'Animals','HARD',  'Pig-like herbivore',              'Has a short trunk'),
    ROW('capybara',   'Animals','HARD',  'Largest rodent',                  'From South America'),
    ROW('wombat',     'Animals','HARD',  'Australian burrowing marsupial', 'Cube-shaped droppings'),
    ROW('echidna',    'Animals','HARD',  'Spiny egg-laying mammal',         'Also called spiny anteater'),
    ROW('ocelot',     'Animals','HARD',  'Small wild cat',                  'Spotted coat'),
    ROW('manatee',    'Animals','HARD',  'Sea cow',                         'Gentle herbivore'),
    ROW('narwhal',    'Animals','HARD',  'Arctic whale',                    'Has a spiral tusk'),
    ROW('wolverine',  'Animals','HARD',  'Fierce weasel relative',          'Very aggressive'),
    ROW('hyena',      'Animals','HARD',  'African carnivore',               'Laughing sound'),
    ROW('meerkat',    'Animals','HARD',  'Small mongoose',                  'Stands upright'),
    ROW('chinchilla', 'Animals','HARD',  'Soft-furred rodent',              'From the Andes'),
    ROW('iguana',     'Animals','HARD',  'Large lizard',                    'Often green'),
    ROW('salamander', 'Animals','HARD',  'Moist-skinned amphibian',         'Can regenerate limbs'),
    ROW('axolotl',    'Animals','HARD',  'Mexican salamander',              'Never fully matures'),
    ROW('albatross',  'Animals','HARD',  'Large seabird',                   'Longest wingspan'),
    ROW('toucan',     'Animals','HARD',  'Bird with large beak',            'Colorful bill'),
    ROW('cassowary',  'Animals','HARD',  'Dangerous flightless bird',       'Has a casque on head'),
    ROW('komodo',     'Animals','HARD',  'Largest lizard',                  'Venomous bite'),
    ROW('mongoose',   'Animals','HARD',  'Snake-fighting mammal',           'Quick reflexes'),
    ROW('lemur',      'Animals','HARD',  'Madagascar primate',              'Big eyes'),
    ROW('okapi',      'Animals','HARD',  'Giraffe relative',                'Striped legs'),
    ROW('aardvark',   'Animals','HARD',  'African burrowing mammal',        'Eats termites'),
    ROW('caracal',    'Animals','HARD',  'Wild cat with ear tufts',         'Can leap high'),
    ROW('quokka',     'Animals','HARD',  'Small Australian marsupial',      'Always looks happy'),
    ROW('binturong',  'Animals','HARD',  'Bearcat',                         'Smells like popcorn'),
    ROW('dugong',     'Animals','HARD',  'Sea cow relative',                'Grazes on seagrass'),
    ROW('kinkajou',   'Animals','HARD',  'Rainforest mammal',               'Has a prehensile tail'),

    -- TECHNOLOGY (Original 12 + 88 new = 100)
    ROW('computer',   'Technology','EASY',  'Electronic device',            'Used for processing data'),
    ROW('phone',      'Technology','EASY',  'Communication device',         'You carry it in your pocket'),
    ROW('mouse',      'Technology','EASY',  'Pointing device',              'Click and drag'),
    ROW('screen',     'Technology','EASY',  'Display surface',              'Shows pixels'),
    ROW('laptop',     'Technology','EASY',  'Portable computer',            'Folds shut'),
    ROW('tablet',     'Technology','EASY',  'Touchscreen device',           'Between phone and laptop'),
    ROW('camera',     'Technology','EASY',  'Takes pictures',               'Say cheese'),
    ROW('printer',    'Technology','EASY',  'Makes paper copies',           'Uses ink or toner'),
    ROW('speaker',    'Technology','EASY',  'Outputs sound',                'Part of audio system'),
    ROW('headphones', 'Technology','EASY',  'Personal audio device',        'Worn on ears'),
    ROW('charger',    'Technology','EASY',  'Powers devices',               'Plugs into wall'),
    ROW('battery',    'Technology','EASY',  'Stores power',                 'Can be rechargeable'),
    ROW('wifi',       'Technology','EASY',  'Wireless internet',            'No cables needed'),
    ROW('email',      'Technology','EASY',  'Electronic mail',              'Digital letters'),
    ROW('password',   'Technology','EASY',  'Secret code',                  'Protects accounts'),
    ROW('website',    'Technology','EASY',  'Online page',                  'Has a URL'),
    ROW('video',      'Technology','EASY',  'Moving pictures',              'Can be streamed'),
    ROW('download',   'Technology','EASY',  'Get from internet',            'Save to device'),
    ROW('upload',     'Technology','EASY',  'Send to internet',             'Share online'),
    ROW('click',      'Technology','EASY',  'Press a button',               'Single or double'),
    ROW('scroll',     'Technology','EASY',  'Move up or down',              'Using wheel or finger'),
    ROW('bluetooth',  'Technology','EASY',  'Wireless connection',          'Named after a Viking king'),
    ROW('remote',     'Technology','EASY',  'Controls from distance',       'For TV and more'),
    ROW('keyboard',   'Technology','MEDIUM','Input device',                 'Has many keys'),
    ROW('software',   'Technology','MEDIUM','Programs and routines',        'Runs on hardware'),
    ROW('internet',   'Technology','MEDIUM','Global computer network',      'The World Wide Web'),
    ROW('database',   'Technology','MEDIUM','Structured set of data',       'Held in a computer'),
    ROW('router',     'Technology','MEDIUM','Network device',               'Directs internet traffic'),
    ROW('server',     'Technology','MEDIUM','Provides services',            'Hosts websites'),
    ROW('browser',    'Technology','MEDIUM','Web viewing program',          'Chrome, Firefox, Safari'),
    ROW('application','Technology','MEDIUM','Software program',             'Also called an app'),
    ROW('cloud',      'Technology','MEDIUM','Remote storage',               'Access from anywhere'),
    ROW('backup',     'Technology','MEDIUM','Copy of data',                 'For safety'),
    ROW('virus',      'Technology','MEDIUM','Malicious software',           'Can damage computers'),
    ROW('firewall',   'Technology','MEDIUM','Security barrier',             'Blocks threats'),
    ROW('monitor',    'Technology','MEDIUM','Display screen',               'External to computer'),
    ROW('webcam',     'Technology','MEDIUM','Video camera',                 'For video calls'),
    ROW('microphone', 'Technology','MEDIUM','Records audio',                'Converts sound to signal'),
    ROW('touchscreen','Technology','MEDIUM','Interactive display',          'Responds to fingers'),
    ROW('smartwatch', 'Technology','MEDIUM','Wearable computer',            'On your wrist'),
    ROW('drone',      'Technology','MEDIUM','Flying robot',                 'Remote controlled'),
    ROW('robot',      'Technology','MEDIUM','Automated machine',            'Does tasks automatically'),
    ROW('streaming',  'Technology','MEDIUM','Real-time media',              'Netflix, Spotify'),
    ROW('podcast',    'Technology','MEDIUM','Audio program',                'Download and listen'),
    ROW('hashtag',    'Technology','MEDIUM','Social media tag',             'Starts with pound sign'),
    ROW('username',   'Technology','MEDIUM','Account identifier',           'Your online name'),
    ROW('notification','Technology','MEDIUM','Alert message',               'Pops up on screen'),
    ROW('screenshot', 'Technology','MEDIUM','Screen capture',               'Image of display'),
    ROW('storage',    'Technology','MEDIUM','Data capacity',                'Measured in bytes'),
    ROW('update',     'Technology','MEDIUM','Software improvement',         'Fixes bugs'),
    ROW('sync',       'Technology','MEDIUM','Synchronize data',             'Keep devices matched'),
    ROW('cache',      'Technology','MEDIUM','Temporary storage',            'Speeds up access'),
    ROW('cookie',     'Technology','MEDIUM','Web tracking data',            'Stored by browser'),
    ROW('pixel',      'Technology','MEDIUM','Smallest display unit',        'Makes up images'),
    ROW('resolution', 'Technology','MEDIUM','Image clarity',                'Measured in pixels'),
    ROW('algorithm',  'Technology','HARD',  'Step-by-step procedure',       'Used for calculations'),
    ROW('encryption', 'Technology','HARD',  'Process of encoding info',     'Keeps data secure'),
    ROW('processor',  'Technology','HARD',  'CPU',                          'The brain of the computer'),
    ROW('bandwidth',  'Technology','HARD',  'Network capacity',             'Data transfer rate'),
    ROW('blockchain', 'Technology','HARD',  'Distributed ledger',           'Powers cryptocurrency'),
    ROW('cryptocurrency','Technology','HARD','Digital currency',            'Bitcoin is one'),
    ROW('metadata',   'Technology','HARD',  'Data about data',              'Describes other data'),
    ROW('protocol',   'Technology','HARD',  'Communication rules',          'HTTP, FTP, etc'),
    ROW('interface',  'Technology','HARD',  'Connection point',             'User interacts with'),
    ROW('latency',    'Technology','HARD',  'Response delay',               'Lower is better'),
    ROW('virtualization','Technology','HARD','Simulated environment',       'Virtual machines'),
    ROW('firmware',   'Technology','HARD',  'Embedded software',            'On hardware chips'),
    ROW('middleware', 'Technology','HARD',  'Software bridge',              'Connects applications'),
    ROW('compiler',   'Technology','HARD',  'Code translator',              'Source to machine code'),
    ROW('debugger',   'Technology','HARD',  'Error finding tool',           'Steps through code'),
    ROW('repository', 'Technology','HARD',  'Code storage',                 'Git uses these'),
    ROW('kernel',     'Technology','HARD',  'Core of operating system',     'Manages resources'),
    ROW('hyperlink',  'Technology','HARD',  'Clickable connection',         'Links to another page'),
    ROW('malware',    'Technology','HARD',  'Harmful software',             'Includes viruses'),
    ROW('phishing',   'Technology','HARD',  'Deceptive attack',             'Tricks users'),
    ROW('ransomware', 'Technology','HARD',  'Encrypts your files',          'Demands payment'),
    ROW('biometrics', 'Technology','HARD',  'Body-based security',          'Fingerprint, face'),
    ROW('proxy',      'Technology','HARD',  'Intermediary server',          'Hides your IP'),
    ROW('throttling', 'Technology','HARD',  'Speed limiting',               'Reduces bandwidth'),
    ROW('compression','Technology','HARD',  'Reduces file size',            'ZIP files'),
    ROW('defragmentation','Technology','HARD','Reorganizing data',          'Speeds up hard drives'),
    ROW('overclocking','Technology','HARD', 'Boosting CPU speed',           'Beyond specifications'),
    ROW('heatsink',   'Technology','HARD',  'Cooling component',            'Dissipates heat'),
    ROW('peripheral', 'Technology','HARD',  'External device',              'Connects to computer'),
    ROW('motherboard','Technology','HARD',  'Main circuit board',           'Components plug into'),
    ROW('transistor', 'Technology','HARD',  'Electronic switch',            'Building block of chips'),
    ROW('semiconductor','Technology','HARD','Conducts partially',           'Silicon is one'),
    ROW('telemetry',  'Technology','HARD',  'Remote measurement',           'Collects usage data'),
    ROW('heuristic',  'Technology','HARD',  'Problem-solving approach',     'Trial and error'),
    ROW('sandbox',    'Technology','HARD',  'Isolated environment',         'For testing safely'),
    ROW('containerization','Technology','HARD','Isolated app deployment',   'Docker uses this'),
    ROW('authentication','Technology','HARD','Identity verification',       'Proves who you are'),
    ROW('scalability','Technology','HARD',  'Growth capacity',              'Handle more load'),
    ROW('redundancy', 'Technology','HARD',  'Backup systems',               'Prevents failure'),
    ROW('obfuscation','Technology','HARD',  'Making unclear',               'Hides code logic'),
    ROW('neural',     'Technology','HARD',  'Brain-inspired computing',     'AI networks'),
    ROW('quantum',    'Technology','HARD',  'Subatomic computing',          'Uses qubits'),
    ROW('hologram',   'Technology','HARD',  'Three-D image',                'Made with lasers'),
    ROW('nanotechnology','Technology','HARD','Tiny scale engineering',      'Molecular level'),
    ROW('augmented',  'Technology','HARD',  'Enhanced reality',             'Overlays digital info'),

    -- FRUITS (Original 12 + 88 new = 100)
    ROW('apple',      'Fruits','EASY',  'Red or green fruit',               'Keeps the doctor away'),
    ROW('banana',     'Fruits','EASY',  'Yellow curved fruit',              'Monkeys love it'),
    ROW('orange',     'Fruits','EASY',  'Citrus fruit',                     'Same name as its color'),
    ROW('grape',      'Fruits','EASY',  'Small round fruit',                'Grows in bunches on vines'),
    ROW('lemon',      'Fruits','EASY',  'Sour yellow citrus',               'Makes lemonade'),
    ROW('lime',       'Fruits','EASY',  'Small green citrus',               'In many drinks'),
    ROW('peach',      'Fruits','EASY',  'Fuzzy stone fruit',                'Pink and orange'),
    ROW('pear',       'Fruits','EASY',  'Bell-shaped fruit',                'Green or brown'),
    ROW('plum',       'Fruits','EASY',  'Purple stone fruit',               'Sweet and juicy'),
    ROW('cherry',     'Fruits','EASY',  'Small red fruit',                  'Often in pairs'),
    ROW('coconut',    'Fruits','EASY',  'Tropical hard fruit',              'Has white flesh'),
    ROW('melon',      'Fruits','EASY',  'Large sweet fruit',                'Many varieties'),
    ROW('apricot',    'Fruits','EASY',  'Small orange fruit',               'Similar to peach'),
    ROW('fig',        'Fruits','EASY',  'Sweet purple fruit',               'Has many seeds inside'),
    ROW('date',       'Fruits','EASY',  'Sweet dried fruit',                'Grows on palm trees'),
    ROW('avocado',    'Fruits','EASY',  'Green creamy fruit',               'Good for guacamole'),
    ROW('tomato',     'Fruits','EASY',  'Red salad fruit',                  'Often called vegetable'),
    ROW('mango',      'Fruits','MEDIUM','Tropical stone fruit',             'Sweet and juicy'),
    ROW('pineapple',  'Fruits','MEDIUM','Tropical fruit with spikes',       'SpongeBob lives in one'),
    ROW('strawberry', 'Fruits','MEDIUM','Red fruit with seeds on outside',  'Great in shortcake'),
    ROW('watermelon', 'Fruits','MEDIUM','Large fruit with green rind',      'Red inside with black seeds'),
    ROW('raspberry',  'Fruits','MEDIUM','Small red berry',                  'Hollow inside'),
    ROW('blackberry', 'Fruits','MEDIUM','Dark purple berry',                'Grows on thorny bushes'),
    ROW('cranberry',  'Fruits','MEDIUM','Tart red berry',                   'Popular at Thanksgiving'),
    ROW('grapefruit', 'Fruits','MEDIUM','Large sour citrus',                'Pink or yellow flesh'),
    ROW('papaya',     'Fruits','MEDIUM','Tropical orange fruit',            'Has black seeds'),
    ROW('guava',      'Fruits','MEDIUM','Tropical pink fruit',              'Strong fragrance'),
    ROW('passionfruit','Fruits','MEDIUM','Wrinkled purple fruit',           'Seedy inside'),
    ROW('lychee',     'Fruits','MEDIUM','Asian fruit',                      'Bumpy red skin'),
    ROW('nectarine',  'Fruits','MEDIUM','Smooth-skinned peach',             'No fuzz'),
    ROW('tangerine',  'Fruits','MEDIUM','Small orange citrus',              'Easy to peel'),
    ROW('mandarin',   'Fruits','MEDIUM','Sweet citrus',                     'Segments easily'),
    ROW('clementine', 'Fruits','MEDIUM','Seedless mandarin',                'Popular snack'),
    ROW('kumquat',    'Fruits','MEDIUM','Tiny citrus',                      'Eat skin and all'),
    ROW('persimmon', 'Fruits','MEDIUM','Orange autumn fruit',              'Sweet when ripe'),
    ROW('mulberry',   'Fruits','MEDIUM','Berry from trees',                 'Red to purple'),
    ROW('gooseberry', 'Fruits','MEDIUM','Tart green berry',                 'Striped skin'),
    ROW('currant',    'Fruits','MEDIUM','Tiny berry',                       'Red, black, or white'),
    ROW('plantain',   'Fruits','MEDIUM','Cooking banana',                   'Less sweet'),
    ROW('jackfruit',  'Fruits','MEDIUM','Large spiky fruit',                'World''s largest tree fruit'),
    ROW('breadfruit', 'Fruits','MEDIUM','Starchy tropical fruit',           'Like bread when cooked'),
    ROW('starfruit',  'Fruits','MEDIUM','Star-shaped when sliced',          'Yellow and waxy'),
    ROW('dragonfruit','Fruits','MEDIUM','Pink scaly fruit',                 'White or red inside'),
    ROW('kiwifruit',  'Fruits','HARD',  'Small oval fruit',                 'Fuzzy brown outside, green inside'),
    ROW('pomegranate','Fruits','HARD',  'Fruit with many red seeds',        'Name means "apple with many seeds"'),
    ROW('cantaloupe', 'Fruits','HARD',  'Type of melon',                    'Has an orange, sweet flesh'),
    ROW('blueberry',  'Fruits','HARD',  'Small blue fruit',                 'Often used in muffins'),
    ROW('honeydew',   'Fruits','HARD',  'Green melon',                      'Sweet and mild'),
    ROW('durian',     'Fruits','HARD',  'Smelly Asian fruit',               'Banned in some hotels'),
    ROW('rambutan',   'Fruits','HARD',  'Hairy red fruit',                  'Related to lychee'),
    ROW('longan',     'Fruits','HARD',  'Dragon eye fruit',                 'Similar to lychee'),
    ROW('mangosteen', 'Fruits','HARD',  'Purple tropical fruit',            'Queen of fruits'),
    ROW('soursop',    'Fruits','HARD',  'Spiky green fruit',                'Creamy white flesh'),
    ROW('cherimoya',  'Fruits','HARD',  'Scaly green fruit',                'Custard apple'),
    ROW('tamarind',   'Fruits','HARD',  'Sour pod fruit',                   'Used in sauces'),
    ROW('quince',     'Fruits','HARD',  'Yellow pear-like fruit',           'Best when cooked'),
    ROW('medlar',     'Fruits','HARD',  'Old-fashioned fruit',              'Eaten when bletted'),
    ROW('loquat',     'Fruits','HARD',  'Small orange fruit',               'Also called Japanese plum'),
    ROW('jujube',     'Fruits','HARD',  'Chinese date',                     'Red when ripe'),
    ROW('feijoa',     'Fruits','HARD',  'Green oval fruit',                 'Pineapple guava'),
    ROW('cactus',     'Fruits','HARD',  'Prickly pear fruit',               'From desert plants'),
    ROW('acai',       'Fruits','HARD',  'Purple Amazonian berry',           'Popular in bowls'),
    ROW('goji',       'Fruits','HARD',  'Red superfood berry',              'From Asia'),
    ROW('elderberry', 'Fruits','HARD',  'Dark purple berry',                'Used in medicine'),
    ROW('boysenberry','Fruits','HARD',  'Hybrid berry',                     'Cross of several berries'),
    ROW('loganberry', 'Fruits','HARD',  'Raspberry-blackberry hybrid',      'Named after its creator'),
    ROW('marionberry','Fruits','HARD',  'Type of blackberry',               'From Oregon'),
    ROW('cloudberry', 'Fruits','HARD',  'Arctic orange berry',              'Grows in cold regions'),
    ROW('salmonberry','Fruits','HARD',  'Pink to red berry',                'Pacific Northwest native'),
    ROW('huckleberry','Fruits','HARD',  'Wild blueberry relative',          'Found in forests'),
    ROW('pawpaw',     'Fruits','HARD',  'North American fruit',             'Tastes tropical'),
    ROW('sapodilla',  'Fruits','HARD',  'Brown tropical fruit',             'Very sweet'),
    ROW('carambola',  'Fruits','HARD',  'Another name for starfruit',       'Five-pointed slices'),
    ROW('cupuacu',    'Fruits','HARD',  'Amazonian cacao relative',         'Makes chocolate alternative'),
    ROW('jabuticaba', 'Fruits','HARD',  'Brazilian grape',                  'Grows on trunk'),
    ROW('pitaya',     'Fruits','HARD',  'Another name for dragonfruit',     'From cactus'),
    ROW('rollinia',   'Fruits','HARD',  'Bumpy yellow fruit',               'Lemon meringue flavor'),
    ROW('mamey',      'Fruits','HARD',  'Central American fruit',           'Orange flesh'),
    ROW('lucuma',     'Fruits','HARD',  'Peruvian fruit',                   'Dry sweet flesh'),
    ROW('camu',       'Fruits','HARD',  'Amazonian sour fruit',             'Highest vitamin C'),
    ROW('noni',       'Fruits','HARD',  'Strong-smelling fruit',            'Used medicinally'),
    ROW('santol',     'Fruits','HARD',  'Southeast Asian fruit',            'Cotton-like flesh'),
    ROW('snakefruit', 'Fruits','HARD',  'Scaly Indonesian fruit',           'Also called salak'),
    ROW('wax',        'Fruits','HARD',  'Bell-shaped Asian fruit',          'Rose apple'),
    ROW('miracle',    'Fruits','HARD',  'Makes sour taste sweet',           'West African berry'),
    ROW('african',    'Fruits','HARD',  'Cherry-like fruit',                'Bitter outer pulp'),
    ROW('ackee',      'Fruits','HARD',  'Jamaican national fruit',          'Must be ripe to eat'),
    ROW('ugli',       'Fruits','HARD',  'Wrinkly citrus hybrid',            'From Jamaica'),
    ROW('yuzu',       'Fruits','HARD',  'Japanese citrus',                  'Used in cuisine'),
    ROW('citron',     'Fruits','HARD',  'Ancient citrus',                   'Mostly rind'),
    ROW('bergamot',   'Fruits','HARD',  'Aromatic citrus',                  'Flavors Earl Grey tea'),
    ROW('pomelo',     'Fruits','HARD',  'Largest citrus',                   'Ancestor of grapefruit'),
    ROW('calamansi',  'Fruits','HARD',  'Philippine citrus',                'Very sour'),
    ROW('finger',     'Fruits','HARD',  'Caviar lime',                      'Tiny pearl-like beads'),
    ROW('blood',      'Fruits','HARD',  'Red-fleshed orange',               'Dark juice'),
    ROW('cara',       'Fruits','HARD',  'Pink navel orange',                'Sweeter variety'),
    ROW('seville',    'Fruits','HARD',  'Bitter orange',                    'For marmalade'),
    ROW('oro',        'Fruits','HARD',  'Golden citrus hybrid',             'Grapefruit-orange mix'),

    -- PROGRAMMING (Original 12 + 88 new = 100)
    ROW('java',       'Programming','EASY',  'A programming language',      'Coffee logo'),
    ROW('code',       'Programming','EASY',  'Instructions for a computer', 'Written by programmers'),
    ROW('bug',        'Programming','EASY',  'Error in software',           'Makes things crash'),
    ROW('loop',       'Programming','EASY',  'Repeats a block of code',     'For, while, do-while'),
    ROW('python',     'Programming','EASY',  'Popular language',            'Named after comedy group'),
    ROW('html',       'Programming','EASY',  'Web markup language',         'Structures web pages'),
    ROW('css',        'Programming','EASY',  'Styles web pages',            'Colors and layouts'),
    ROW('script',     'Programming','EASY',  'Set of commands',             'Runs automatically'),
    ROW('file',       'Programming','EASY',  'Stored data unit',            'Has a name and extension'),
    ROW('folder',     'Programming','EASY',  'Contains files',              'Directory'),
    ROW('save',       'Programming','EASY',  'Store to disk',               'Preserves work'),
    ROW('print',      'Programming','EASY',  'Output to screen',            'Display text'),
    ROW('input',      'Programming','EASY',  'User provided data',          'Keyboard or mouse'),
    ROW('output',     'Programming','EASY',  'Program result',              'Screen or file'),
    ROW('string',     'Programming','EASY',  'Text data type',              'In quotes'),
    ROW('number',     'Programming','EASY',  'Numeric data',                'Integer or float'),
    ROW('array',      'Programming','EASY',  'List of items',               'Indexed collection'),
    ROW('debug',      'Programming','EASY',  'Find errors',                 'Fix problems'),
    ROW('run',        'Programming','EASY',  'Execute program',             'Start the code'),
    ROW('error',      'Programming','EASY',  'Something went wrong',        'Needs fixing'),
    ROW('syntax',     'Programming','EASY',  'Code grammar',                'Rules of language'),
    ROW('comment',    'Programming','EASY',  'Note in code',                'Not executed'),
    ROW('variable',   'Programming','MEDIUM','Data storage location',       'Has a name and value'),
    ROW('function',   'Programming','MEDIUM','Reusable block of code',      'Takes inputs and returns output'),
    ROW('boolean',    'Programming','MEDIUM','True or false',               'Named after George Boole'),
    ROW('iterator',   'Programming','MEDIUM','Loops through items',         'Used in for-each loops'),
    ROW('class',      'Programming','MEDIUM','Blueprint for objects',       'Object-oriented concept'),
    ROW('object',     'Programming','MEDIUM','Instance of a class',         'Has properties and methods'),
    ROW('method',     'Programming','MEDIUM','Function in a class',         'Behavior of object'),
    ROW('parameter',  'Programming','MEDIUM','Function input',              'Passed in'),
    ROW('argument',   'Programming','MEDIUM','Value passed to function',    'Actual data'),
    ROW('return',     'Programming','MEDIUM','Give back value',             'End of function'),
    ROW('null',       'Programming','MEDIUM','No value',                    'Empty reference'),
    ROW('integer',    'Programming','MEDIUM','Whole number type',           'No decimals'),
    ROW('float',      'Programming','MEDIUM','Decimal number type',         'Has decimal point'),
    ROW('double',     'Programming','MEDIUM','Precise decimal type',        'More precision'),
    ROW('char',       'Programming','MEDIUM','Single character',            'One letter'),
    ROW('constant',   'Programming','MEDIUM','Unchanging value',            'Cannot be modified'),
    ROW('operator',   'Programming','MEDIUM','Symbol for operation',        'Plus, minus, etc'),
    ROW('condition',  'Programming','MEDIUM','Test expression',             'If statements'),
    ROW('branch',     'Programming','MEDIUM','Code path decision',          'If-else'),
    ROW('exception',  'Programming','MEDIUM','Runtime error',               'Can be caught'),
    ROW('try',        'Programming','MEDIUM','Attempt risky code',          'Part of error handling'),
    ROW('catch',      'Programming','MEDIUM','Handle exception',            'After try block'),
    ROW('throw',      'Programming','MEDIUM','Raise exception',             'Signal error'),
    ROW('import',     'Programming','MEDIUM','Include library',             'Use external code'),
    ROW('export',     'Programming','MEDIUM','Share code',                  'Make available'),
    ROW('module',     'Programming','MEDIUM','Code unit',                   'Reusable package'),
    ROW('library',    'Programming','MEDIUM','Collection of code',          'Pre-written functions'),
    ROW('framework',  'Programming','MEDIUM','Application structure',       'Provides scaffolding'),
    ROW('api',        'Programming','MEDIUM','Interface for programs',      'Application programming interface'),
    ROW('json',       'Programming','MEDIUM','Data format',                 'Curly braces'),
    ROW('xml',        'Programming','MEDIUM','Markup data format',          'Angle brackets'),
    ROW('git',        'Programming','MEDIUM','Version control',             'Track changes'),
    ROW('commit',     'Programming','MEDIUM','Save changes to repo',        'Git operation'),
    ROW('merge',      'Programming','MEDIUM','Combine branches',            'Git operation'),
    ROW('push',       'Programming','MEDIUM','Send to remote',              'Git operation'),
    ROW('pull',       'Programming','MEDIUM','Get from remote',             'Git operation'),
    ROW('polymorphism','Programming','HARD', 'Many forms',                  'Object-oriented concept'),
    ROW('encapsulation','Programming','HARD','Bundling of data',            'Hiding internal state'),
    ROW('inheritance','Programming','HARD',  'Deriving from a class',       'Is-a relationship'),
    ROW('recursion',  'Programming','HARD',  'Function calling itself',     'Requires a base case'),
    ROW('abstraction','Programming','HARD',  'Hiding complexity',           'Show only essentials'),
    ROW('interface',  'Programming','HARD',  'Contract for classes',        'Methods without body'),
    ROW('generic',    'Programming','HARD',  'Type parameter',              'Works with any type'),
    ROW('lambda',     'Programming','HARD',  'Anonymous function',          'Inline function'),
    ROW('closure',    'Programming','HARD',  'Function with environment',   'Captures variables'),
    ROW('callback',   'Programming','HARD',  'Function passed as argument', 'Called later'),
    ROW('promise',    'Programming','HARD',  'Future value',                'Asynchronous result'),
    ROW('async',      'Programming','HARD',  'Non-blocking code',           'Concurrent execution'),
    ROW('await',      'Programming','HARD',  'Wait for promise',            'Pause async function'),
    ROW('thread',     'Programming','HARD',  'Execution path',              'Parallel processing'),
    ROW('mutex',      'Programming','HARD',  'Lock mechanism',              'Prevent race conditions'),
    ROW('deadlock',   'Programming','HARD',  'Stuck processes',             'Waiting for each other'),
    ROW('semaphore',  'Programming','HARD',  'Signaling mechanism',         'Control access'),
    ROW('singleton',  'Programming','HARD',  'One instance pattern',        'Design pattern'),
    ROW('factory',    'Programming','HARD',  'Object creation pattern',     'Design pattern'),
    ROW('observer',   'Programming','HARD',  'Event pattern',               'Notify subscribers'),
    ROW('decorator',  'Programming','HARD',  'Wrapper pattern',             'Add functionality'),
    ROW('facade',     'Programming','HARD',  'Simple interface pattern',    'Hide complexity'),
    ROW('adapter',    'Programming','HARD',  'Compatibility pattern',       'Convert interface'),
    ROW('proxy',      'Programming','HARD',  'Stand-in pattern',            'Control access'),
    ROW('memoization','Programming','HARD',  'Cache results',               'Optimization technique'),
    ROW('serialization','Programming','HARD','Convert to bytes',            'Save object state'),
    ROW('deserialization','Programming','HARD','Bytes to object',           'Restore state'),
    ROW('refactoring','Programming','HARD',  'Improve code structure',      'Without changing behavior'),
    ROW('dependency', 'Programming','HARD',  'Required component',          'External requirement'),
    ROW('injection',  'Programming','HARD',  'Provide dependencies',        'Inversion of control'),
    ROW('coupling',   'Programming','HARD',  'Component connection',        'Lower is better'),
    ROW('cohesion',   'Programming','HARD',  'Component focus',             'Higher is better'),
    ROW('immutable',  'Programming','HARD',  'Cannot change',               'Thread safe'),
    ROW('volatile',   'Programming','HARD',  'May change unexpectedly',     'Memory keyword'),
    ROW('heap',       'Programming','HARD',  'Dynamic memory',              'Allocated at runtime'),
    ROW('stack',      'Programming','HARD',  'Memory structure',            'Last in first out'),
    ROW('queue',      'Programming','HARD',  'Data structure',              'First in first out'),
    ROW('tree',       'Programming','HARD',  'Hierarchical structure',      'Has root and nodes'),
    ROW('graph',      'Programming','HARD',  'Network structure',           'Nodes and edges'),
    ROW('hash',       'Programming','HARD',  'Quick lookup structure',      'Key-value pairs'),
    ROW('binary',     'Programming','HARD',  'Base two',                    'Zeros and ones'),
    ROW('hexadecimal','Programming','HARD',  'Base sixteen',                'Uses A-F'),

    -- SPORTS (Original 12 + 88 new = 100)
    ROW('ball',       'Sports','EASY',  'Round object',                     'Used in many games'),
    ROW('goal',       'Sports','EASY',  'Scoring area',                     'Aim here to win'),
    ROW('run',        'Sports','EASY',  'Move fast',                        'Faster than walking'),
    ROW('jump',       'Sports','EASY',  'Leap into air',                    'Go up and down'),
    ROW('kick',       'Sports','EASY',  'Strike with foot',                 'Soccer move'),
    ROW('throw',      'Sports','EASY',  'Send through air',                 'Using arm'),
    ROW('catch',      'Sports','EASY',  'Grab object',                      'With hands'),
    ROW('swim',       'Sports','EASY',  'Move in water',                    'Uses strokes'),
    ROW('race',       'Sports','EASY',  'Speed competition',                'First wins'),
    ROW('team',       'Sports','EASY',  'Group of players',                 'Work together'),
    ROW('score',      'Sports','EASY',  'Points earned',                    'Winner has most'),
    ROW('win',        'Sports','EASY',  'Be victorious',                    'Beat opponents'),
    ROW('lose',       'Sports','EASY',  'Not win',                          'Opposite of win'),
    ROW('tie',        'Sports','EASY',  'Same score',                       'Draw'),
    ROW('coach',      'Sports','EASY',  'Trains players',                   'Makes strategy'),
    ROW('player',     'Sports','EASY',  'Participant',                      'In the game'),
    ROW('game',       'Sports','EASY',  'Match or contest',                 'Play to win'),
    ROW('match',      'Sports','EASY',  'Competitive event',                'Two sides compete'),
    ROW('field',      'Sports','EASY',  'Playing surface',                  'Grass usually'),
    ROW('court',      'Sports','EASY',  'Playing area',                     'Tennis or basketball'),
    ROW('net',        'Sports','EASY',  'Mesh barrier',                     'Ball goes over'),
    ROW('bat',        'Sports','EASY',  'Hitting tool',                     'Used in baseball'),
    ROW('soccer',     'Sports','MEDIUM','Played with feet',                 'Also known as football'),
    ROW('tennis',     'Sports','MEDIUM','Played with rackets',              'Over a net'),
    ROW('baseball',   'Sports','MEDIUM','Hit a ball with a bat',            'Run the bases'),
    ROW('hockey',     'Sports','MEDIUM','Played on ice',                    'Use a puck and stick'),
    ROW('basketball', 'Sports','MEDIUM','Played with hoop',                 'Bounce and shoot'),
    ROW('football',   'Sports','MEDIUM','American sport',                   'Touchdowns'),
    ROW('golf',       'Sports','MEDIUM','Club and ball',                    'Into the hole'),
    ROW('swimming',   'Sports','MEDIUM','Water sport',                      'Laps in pool'),
    ROW('cycling',    'Sports','MEDIUM','Bicycle racing',                   'Pedal power'),
    ROW('boxing',     'Sports','MEDIUM','Combat sport',                     'Punching'),
    ROW('skiing',     'Sports','MEDIUM','Snow sport',                       'Down the mountain'),
    ROW('surfing',    'Sports','MEDIUM','Wave riding',                      'On a board'),
    ROW('bowling',    'Sports','MEDIUM','Knock down pins',                  'Roll the ball'),
    ROW('archery',    'Sports','MEDIUM','Bow and arrow',                    'Hit the target'),
    ROW('fencing',    'Sports','MEDIUM','Sword fighting sport',             'Foil, epee, or saber'),
    ROW('rowing',     'Sports','MEDIUM','Boat racing',                      'Oars in water'),
    ROW('sailing',    'Sports','MEDIUM','Wind-powered boats',               'Uses sails'),
    ROW('diving',     'Sports','MEDIUM','Jump into water',                  'From high board'),
    ROW('skating',    'Sports','MEDIUM','Glide on ice',                     'Figure or speed'),
    ROW('karate',     'Sports','MEDIUM','Martial art',                      'From Japan'),
    ROW('judo',       'Sports','MEDIUM','Throwing martial art',             'Olympic sport'),
    ROW('taekwondo',  'Sports','MEDIUM','Korean martial art',               'Powerful kicks'),
    ROW('cricket',    'Sports','MEDIUM','Bat and ball sport',               'Popular in UK and India'),
    ROW('rugby',      'Sports','MEDIUM','Like football',                    'Oval ball'),
    ROW('lacrosse',   'Sports','MEDIUM','Stick with net',                   'Native American origin'),
    ROW('handball',   'Sports','MEDIUM','Throw into goal',                  'Fast-paced'),
    ROW('polo',       'Sports','MEDIUM','On horseback',                     'With mallets'),
    ROW('squash',     'Sports','MEDIUM','Racket sport',                     'In enclosed court'),
    ROW('racquetball','Sports','MEDIUM','Similar to squash',                'Larger racket'),
    ROW('triathlon',  'Sports','MEDIUM','Three events',                     'Swim, bike, run'),
    ROW('marathon',   'Sports','MEDIUM','Long distance run',                '26.2 miles'),
    ROW('sprint',     'Sports','MEDIUM','Short fast race',                  '100 meters'),
    ROW('hurdles',    'Sports','MEDIUM','Jump over barriers',               'While running'),
    ROW('javelin',    'Sports','MEDIUM','Throwing spear',                   'Track and field'),
    ROW('discus',     'Sports','MEDIUM','Throwing disk',                    'Track and field'),
    ROW('gymnastics', 'Sports','HARD',  'Physical exercises',               'Requires balance and flexibility'),
    ROW('volleyball', 'Sports','HARD',  'Hit a ball over a net',            'Don''t let it touch the floor'),
    ROW('badminton',  'Sports','HARD',  'Played with a shuttlecock',        'Racket sport'),
    ROW('wrestling',  'Sports','HARD',  'Combat sport',                     'Grappling and throws'),
    ROW('weightlifting','Sports','HARD','Lifting barbells',                 'Snatch and clean'),
    ROW('pentathlon', 'Sports','HARD',  'Five events',                      'Modern Olympic sport'),
    ROW('decathlon',  'Sports','HARD',  'Ten events',                       'Over two days'),
    ROW('biathlon',   'Sports','HARD',  'Skiing and shooting',              'Winter sport'),
    ROW('bobsled',    'Sports','HARD',  'Ice track racing',                 'In a sled'),
    ROW('luge',       'Sports','HARD',  'Feet-first sled',                  'Very fast'),
    ROW('skeleton',   'Sports','HARD',  'Head-first sled',                  'On ice track'),
    ROW('curling',    'Sports','HARD',  'Stones on ice',                    'Sweeping'),
    ROW('snowboarding','Sports','HARD', 'Board on snow',                    'Halfpipe'),
    ROW('paragliding','Sports','HARD',  'Flying with parachute',            'Thermal soaring'),
    ROW('kitesurfing','Sports','HARD',  'Kite pulls on water',              'Board sport'),
    ROW('wakeboarding','Sports','HARD', 'Pulled behind boat',               'On a board'),
    ROW('parkour',    'Sports','HARD',  'Urban movement',                   'Jumping and climbing'),
    ROW('bouldering', 'Sports','HARD',  'Rock climbing',                    'Without ropes'),
    ROW('rappelling', 'Sports','HARD',  'Descending ropes',                 'Down cliffs'),
    ROW('orienteering','Sports','HARD', 'Navigation race',                  'With map and compass'),
    ROW('equestrian', 'Sports','HARD',  'Horse riding',                     'Dressage and jumping'),
    ROW('dressage',   'Sports','HARD',  'Horse dancing',                    'Precise movements'),
    ROW('polo',       'Sports','HARD',  'Horse and mallet',                 'Hit the ball'),
    ROW('steeplechase','Sports','HARD', 'Horse jumping race',               'Over obstacles'),
    ROW('motorsport', 'Sports','HARD',  'Vehicle racing',                   'Cars or motorcycles'),
    ROW('motocross',  'Sports','HARD',  'Motorcycle off-road',              'Dirt bikes'),
    ROW('autocross',  'Sports','HARD',  'Car obstacle course',              'Timed runs'),
    ROW('rallying',   'Sports','HARD',  'Off-road car racing',              'Point to point'),
    ROW('drifting',   'Sports','HARD',  'Controlled sliding',               'In cars'),
    ROW('freerunning','Sports','HARD',  'Creative movement',                'Similar to parkour'),
    ROW('capoeira',   'Sports','HARD',  'Brazilian martial art',            'Dance-like'),
    ROW('kendo',      'Sports','HARD',  'Japanese sword art',               'Bamboo swords'),
    ROW('aikido',     'Sports','HARD',  'Defensive martial art',            'Redirecting force'),
    ROW('sumo',       'Sports','HARD',  'Japanese wrestling',               'Very large athletes'),
    ROW('kickboxing', 'Sports','HARD',  'Punches and kicks',                'Combat sport'),
    ROW('muay',       'Sports','HARD',  'Thai boxing',                      'Eight limbs'),
    ROW('sambo',      'Sports','HARD',  'Russian martial art',              'Military origin'),
    ROW('pickleball', 'Sports','HARD',  'Paddle sport',                     'Like mini tennis'),
    ROW('paddleball', 'Sports','HARD',  'Similar to squash',                'One wall'),
    ROW('sepak',      'Sports','HARD',  'Kick volleyball',                  'Southeast Asian'),
    ROW('kabaddi',    'Sports','HARD',  'Tag wrestling',                    'Indian sport'),
    ROW('pelota',     'Sports','HARD',  'Basque ball game',                 'Very fast'),
    ROW('jai',        'Sports','HARD',  'Fast ball sport',                  'Curved basket'),

    -- FOOD (New category - 100 words)
    ROW('bread',      'Food','EASY',  'Baked staple',                       'Made from flour'),
    ROW('rice',       'Food','EASY',  'Grain staple',                       'Asian cuisine'),
    ROW('pasta',      'Food','EASY',  'Italian staple',                     'Noodles'),
    ROW('cheese',     'Food','EASY',  'Dairy product',                      'Made from milk'),
    ROW('egg',        'Food','EASY',  'From chickens',                      'Breakfast staple'),
    ROW('butter',     'Food','EASY',  'Dairy spread',                       'Creamy and yellow'),
    ROW('milk',       'Food','EASY',  'From cows',                          'White liquid'),
    ROW('meat',       'Food','EASY',  'Animal protein',                     'Beef, pork, chicken'),
    ROW('chicken',    'Food','EASY',  'Poultry',                            'Most common meat'),
    ROW('beef',       'Food','EASY',  'From cattle',                        'Red meat'),
    ROW('pork',       'Food','EASY',  'From pigs',                          'Bacon source'),
    ROW('fish',       'Food','EASY',  'Seafood',                            'From the ocean'),
    ROW('soup',       'Food','EASY',  'Liquid food',                        'Eaten with spoon'),
    ROW('salad',      'Food','EASY',  'Raw vegetables',                     'Often with dressing'),
    ROW('pizza',      'Food','EASY',  'Italian dish',                       'Round with toppings'),
    ROW('burger',     'Food','EASY',  'Ground meat patty',                  'In a bun'),
    ROW('sandwich',   'Food','EASY',  'Between bread',                      'Portable meal'),
    ROW('hotdog',     'Food','EASY',  'Sausage in bun',                     'Baseball food'),
    ROW('taco',       'Food','EASY',  'Mexican food',                       'In a shell'),
    ROW('cake',       'Food','EASY',  'Sweet dessert',                      'For birthdays'),
    ROW('cookie',     'Food','EASY',  'Sweet snack',                        'Baked treat'),
    ROW('candy',      'Food','EASY',  'Sweet treat',                        'Sugar based'),
    ROW('chocolate',  'Food','EASY',  'Sweet from cacao',                   'Dark or milk'),
    ROW('ice',        'Food','EASY',  'Frozen dessert',                     'Comes in cone'),
    ROW('noodle',     'Food','MEDIUM','Long pasta',                         'Asian or Italian'),
    ROW('sushi',      'Food','MEDIUM','Japanese dish',                      'Raw fish and rice'),
    ROW('curry',      'Food','MEDIUM','Spiced dish',                        'Indian or Thai'),
    ROW('stew',       'Food','MEDIUM','Slow-cooked dish',                   'Meat and vegetables'),
    ROW('roast',      'Food','MEDIUM','Oven-cooked',                        'Often Sunday meal'),
    ROW('grill',      'Food','MEDIUM','Cooked over fire',                   'BBQ style'),
    ROW('fry',        'Food','MEDIUM','Cooked in oil',                      'Crispy result'),
    ROW('bake',       'Food','MEDIUM','Oven cooking',                       'Bread and cakes'),
    ROW('steam',      'Food','MEDIUM','Cooked with vapor',                  'Healthy method'),
    ROW('sauce',      'Food','MEDIUM','Liquid condiment',                   'Adds flavor'),
    ROW('gravy',      'Food','MEDIUM','Meat sauce',                         'On potatoes'),
    ROW('broth',      'Food','MEDIUM','Meat or vegetable liquid',           'Soup base'),
    ROW('dumpling',   'Food','MEDIUM','Filled dough',                       'Steamed or fried'),
    ROW('ravioli',    'Food','MEDIUM','Filled pasta',                       'Italian'),
    ROW('lasagna',    'Food','MEDIUM','Layered pasta',                      'Italian'),
    ROW('risotto',    'Food','MEDIUM','Creamy rice',                        'Italian'),
    ROW('paella',     'Food','MEDIUM','Spanish rice dish',                  'With seafood'),
    ROW('burrito',    'Food','MEDIUM','Wrapped tortilla',                   'Mexican'),
    ROW('quesadilla', 'Food','MEDIUM','Cheese tortilla',                    'Mexican'),
    ROW('enchilada',  'Food','MEDIUM','Rolled tortilla',                    'With sauce'),
    ROW('falafel',    'Food','MEDIUM','Fried chickpea balls',               'Middle Eastern'),
    ROW('hummus',     'Food','MEDIUM','Chickpea dip',                       'Middle Eastern'),
    ROW('kebab',      'Food','MEDIUM','Grilled meat skewer',                'Middle Eastern'),
    ROW('teriyaki',   'Food','MEDIUM','Japanese glaze',                     'Sweet and savory'),
    ROW('tempura',    'Food','MEDIUM','Japanese fried',                     'Light batter'),
    ROW('ramen',      'Food','MEDIUM','Japanese noodle soup',               'With broth'),
    ROW('pho',        'Food','MEDIUM','Vietnamese soup',                    'Beef or chicken'),
    ROW('kimchi',     'Food','MEDIUM','Korean fermented',                   'Spicy cabbage'),
    ROW('tofu',       'Food','MEDIUM','Soy product',                        'Vegetarian protein'),
    ROW('tempeh',     'Food','MEDIUM','Fermented soy',                      'Indonesian'),
    ROW('quinoa',     'Food','MEDIUM','Ancient grain',                      'High protein'),
    ROW('couscous',   'Food','MEDIUM','North African grain',                'Tiny pasta'),
    ROW('polenta',    'Food','MEDIUM','Cornmeal dish',                      'Italian'),
    ROW('gnocchi',    'Food','MEDIUM','Potato pasta',                       'Italian'),
    ROW('prosciutto', 'Food','HARD',  'Italian cured ham',                  'Thinly sliced'),
    ROW('carpaccio',  'Food','HARD',  'Raw thin meat',                      'Italian appetizer'),
    ROW('ceviche',    'Food','HARD',  'Citrus-cured fish',                  'South American'),
    ROW('tartare',    'Food','HARD',  'Raw chopped meat',                   'French'),
    ROW('bouillabaisse','Food','HARD','French fish stew',                   'From Marseille'),
    ROW('ratatouille','Food','HARD',  'French vegetable dish',              'Provencal'),
    ROW('coq',        'Food','HARD',  'Chicken in wine',                    'French classic'),
    ROW('soufflé',    'Food','HARD',  'Puffed dish',                        'Can collapse'),
    ROW('quiche',     'Food','HARD',  'Egg pie',                            'French'),
    ROW('croissant',  'Food','HARD',  'Buttery pastry',                     'Crescent shaped'),
    ROW('brioche',    'Food','HARD',  'Rich bread',                         'French'),
    ROW('focaccia',   'Food','HARD',  'Italian flatbread',                  'Olive oil'),
    ROW('ciabatta',   'Food','HARD',  'Italian white bread',                'Crusty'),
    ROW('panettone',  'Food','HARD',  'Italian sweet bread',                'Christmas'),
    ROW('tiramisu',   'Food','HARD',  'Italian dessert',                    'Coffee flavored'),
    ROW('panna',      'Food','HARD',  'Italian cream dessert',              'Jiggly'),
    ROW('gelato',     'Food','HARD',  'Italian ice cream',                  'Denser'),
    ROW('macaron',    'Food','HARD',  'French cookie',                      'Colorful'),
    ROW('madeleine',  'Food','HARD',  'French cake',                        'Shell shaped'),
    ROW('profiterole','Food','HARD',  'Cream puff',                         'French'),
    ROW('éclair',     'Food','HARD',  'Filled pastry',                      'Chocolate topped'),
    ROW('baklava',    'Food','HARD',  'Layered pastry',                     'With honey and nuts'),
    ROW('halva',      'Food','HARD',  'Sweet confection',                   'Middle Eastern'),
    ROW('mochi',      'Food','HARD',  'Rice cake',                          'Japanese'),
    ROW('dango',      'Food','HARD',  'Rice dumpling',                      'Japanese'),
    ROW('gyoza',      'Food','HARD',  'Japanese dumpling',                  'Pan-fried'),
    ROW('udon',       'Food','HARD',  'Thick noodle',                       'Japanese'),
    ROW('soba',       'Food','HARD',  'Buckwheat noodle',                   'Japanese'),
    ROW('bibimbap',   'Food','HARD',  'Korean rice bowl',                   'Mixed'),
    ROW('bulgogi',    'Food','HARD',  'Korean BBQ beef',                    'Marinated'),
    ROW('samosa',     'Food','HARD',  'Indian pastry',                      'Filled triangle'),
    ROW('pakora',     'Food','HARD',  'Indian fritter',                     'Vegetable'),
    ROW('dosa',       'Food','HARD',  'Indian crepe',                       'Fermented'),
    ROW('naan',       'Food','HARD',  'Indian bread',                       'From tandoor'),
    ROW('biryani',    'Food','HARD',  'Indian rice dish',                   'Spiced'),
    ROW('vindaloo',   'Food','HARD',  'Spicy Indian curry',                 'From Goa'),
    ROW('tagine',     'Food','HARD',  'Moroccan stew',                      'Slow-cooked'),
    ROW('shakshuka',  'Food','HARD',  'Eggs in tomato',                     'Middle Eastern'),
    ROW('borscht',    'Food','HARD',  'Beet soup',                          'Eastern European'),
    ROW('pierogi',    'Food','HARD',  'Polish dumpling',                    'Filled'),
    ROW('schnitzel',  'Food','HARD',  'Breaded cutlet',                     'Austrian'),
    ROW('goulash',    'Food','HARD',  'Hungarian stew',                     'Paprika'),

    -- MUSIC (New category - 100 words)
    ROW('song',       'Music','EASY',  'Musical piece',                     'Has melody'),
    ROW('sing',       'Music','EASY',  'Use your voice',                    'Make music'),
    ROW('band',       'Music','EASY',  'Group of musicians',                'Play together'),
    ROW('drum',       'Music','EASY',  'Percussion instrument',             'You hit it'),
    ROW('guitar',     'Music','EASY',  'String instrument',                 'Six strings'),
    ROW('piano',      'Music','EASY',  'Keyboard instrument',               'Black and white keys'),
    ROW('violin',     'Music','EASY',  'String instrument',                 'Played with bow'),
    ROW('flute',      'Music','EASY',  'Wind instrument',                   'Blow across hole'),
    ROW('beat',       'Music','EASY',  'Rhythmic pulse',                    'Keeps time'),
    ROW('note',       'Music','EASY',  'Single sound',                      'Do, re, mi'),
    ROW('tune',       'Music','EASY',  'Melody',                            'Catchy'),
    ROW('loud',       'Music','EASY',  'High volume',                       'Forte'),
    ROW('soft',       'Music','EASY',  'Low volume',                        'Piano'),
    ROW('fast',       'Music','EASY',  'Quick tempo',                       'Allegro'),
    ROW('slow',       'Music','EASY',  'Low tempo',                         'Adagio'),
    ROW('rock',       'Music','EASY',  'Music genre',                       'Electric guitar'),
    ROW('pop',        'Music','EASY',  'Popular music',                     'Mainstream'),
    ROW('jazz',       'Music','EASY',  'Music genre',                       'Improvisation'),
    ROW('blues',      'Music','EASY',  'Music genre',                       'Feeling sad'),
    ROW('country',    'Music','EASY',  'Music genre',                       'Rural America'),
    ROW('rap',        'Music','EASY',  'Spoken rhymes',                     'Hip hop'),
    ROW('dance',      'Music','EASY',  'Move to music',                     'Electronic beats'),
    ROW('chorus',     'Music','MEDIUM','Repeated section',                  'The hook'),
    ROW('verse',      'Music','MEDIUM','Song section',                      'Tells the story'),
    ROW('bridge',     'Music','MEDIUM','Contrasting section',               'Connects parts'),
    ROW('melody',     'Music','MEDIUM','Tune of a song',                    'What you hum'),
    ROW('harmony',    'Music','MEDIUM','Multiple notes',                    'Sound together'),
    ROW('rhythm',     'Music','MEDIUM','Pattern of beats',                  'Keep time'),
    ROW('tempo',      'Music','MEDIUM','Speed of music',                    'Beats per minute'),
    ROW('pitch',      'Music','MEDIUM','High or low',                       'Frequency'),
    ROW('scale',      'Music','MEDIUM','Series of notes',                   'Major or minor'),
    ROW('chord',      'Music','MEDIUM','Notes together',                    'Three or more'),
    ROW('octave',     'Music','MEDIUM','Eight notes',                       'Same note higher'),
    ROW('key',        'Music','MEDIUM','Musical home base',                 'C major, etc'),
    ROW('sharp',      'Music','MEDIUM','Half step up',                      'The symbol'),
    ROW('flat',       'Music','MEDIUM','Half step down',                    'Lower pitch'),
    ROW('bass',       'Music','MEDIUM','Low sounds',                        'Deep tones'),
    ROW('treble',     'Music','MEDIUM','High sounds',                       'High tones'),
    ROW('acoustic',   'Music','MEDIUM','Not electric',                      'Natural sound'),
    ROW('electric',   'Music','MEDIUM','Amplified',                         'Uses power'),
    ROW('synthesizer','Music','MEDIUM','Electronic instrument',             'Makes sounds'),
    ROW('trumpet',    'Music','MEDIUM','Brass instrument',                  'Louis Armstrong'),
    ROW('saxophone',  'Music','MEDIUM','Brass woodwind',                    'Jazz essential'),
    ROW('clarinet',   'Music','MEDIUM','Woodwind',                          'Single reed'),
    ROW('cello',      'Music','MEDIUM','Large string',                      'Deep sound'),
    ROW('harp',       'Music','MEDIUM','Plucked strings',                   'Angelic sound'),
    ROW('harmonica',  'Music','MEDIUM','Mouth organ',                       'Blues instrument'),
    ROW('accordion',  'Music','MEDIUM','Squeezebox',                        'Bellows'),
    ROW('banjo',      'Music','MEDIUM','String instrument',                 'Country folk'),
    ROW('ukulele',    'Music','MEDIUM','Small guitar',                      'Hawaiian'),
    ROW('xylophone',  'Music','MEDIUM','Percussion bars',                   'Hit with mallets'),
    ROW('orchestra',  'Music','MEDIUM','Large ensemble',                    'Classical'),
    ROW('conductor',  'Music','MEDIUM','Leads orchestra',                   'Uses baton'),
    ROW('composer',   'Music','MEDIUM','Writes music',                      'Creates pieces'),
    ROW('musician',   'Music','MEDIUM','Plays music',                       'Artist'),
    ROW('concert',    'Music','MEDIUM','Live performance',                  'In a venue'),
    ROW('album',      'Music','MEDIUM','Collection of songs',               'Released together'),
    ROW('single',     'Music','MEDIUM','One song release',                  'Hit potential'),
    ROW('crescendo',  'Music','HARD',  'Getting louder',                    'Building up'),
    ROW('diminuendo', 'Music','HARD',  'Getting softer',                    'Fading down'),
    ROW('staccato',   'Music','HARD',  'Short detached',                    'Choppy notes'),
    ROW('legato',     'Music','HARD',  'Smooth connected',                  'Flowing'),
    ROW('vibrato',    'Music','HARD',  'Slight pitch variation',            'Wavering'),
    ROW('tremolo',    'Music','HARD',  'Rapid repetition',                  'Trembling'),
    ROW('arpeggio',   'Music','HARD',  'Broken chord',                      'Notes in sequence'),
    ROW('cadence',    'Music','HARD',  'Musical ending',                    'Resolution'),
    ROW('modulation', 'Music','HARD',  'Key change',                        'Shift'),
    ROW('counterpoint','Music','HARD', 'Interweaving melodies',             'Bach style'),
    ROW('fugue',      'Music','HARD',  'Contrapuntal piece',                'Baroque form'),
    ROW('sonata',     'Music','HARD',  'Classical form',                    'Multiple movements'),
    ROW('symphony',   'Music','HARD',  'Large orchestral work',             'Four movements'),
    ROW('concerto',   'Music','HARD',  'Soloist with orchestra',            'Showcases skill'),
    ROW('aria',       'Music','HARD',  'Opera solo',                        'Emotional song'),
    ROW('recitative', 'Music','HARD',  'Speech-like singing',               'In opera'),
    ROW('libretto',   'Music','HARD',  'Opera text',                        'The words'),
    ROW('overture',   'Music','HARD',  'Opening piece',                     'Introduction'),
    ROW('coda',       'Music','HARD',  'Ending section',                    'Conclusion'),
    ROW('fermata',    'Music','HARD',  'Hold the note',                     'Pause'),
    ROW('fortissimo', 'Music','HARD',  'Very loud',                         'ff'),
    ROW('pianissimo', 'Music','HARD',  'Very soft',                         'pp'),
    ROW('sforzando',  'Music','HARD',  'Sudden accent',                     'sf'),
    ROW('rubato',     'Music','HARD',  'Flexible tempo',                    'Expressive'),
    ROW('syncopation','Music','HARD',  'Off-beat accent',                   'Unexpected rhythm'),
    ROW('polyrhythm', 'Music','HARD',  'Multiple rhythms',                  'At once'),
    ROW('atonality',  'Music','HARD',  'No key center',                     'Dissonant'),
    ROW('chromatic',  'Music','HARD',  'All twelve tones',                  'Half steps'),
    ROW('diatonic',   'Music','HARD',  'Within the key',                    'Natural notes'),
    ROW('pentatonic', 'Music','HARD',  'Five note scale',                   'Simple'),
    ROW('modal',      'Music','HARD',  'Using modes',                       'Dorian, etc'),
    ROW('glissando',  'Music','HARD',  'Sliding notes',                     'Continuous'),
    ROW('portamento', 'Music','HARD',  'Carrying note',                     'Smooth slide'),
    ROW('solfege',    'Music','HARD',  'Singing syllables',                 'Do re mi'),
    ROW('timbre',     'Music','HARD',  'Tone color',                        'Instrument quality'),
    ROW('resonance',  'Music','HARD',  'Sound amplification',               'Vibration'),
    ROW('dissonance', 'Music','HARD',  'Clashing sounds',                   'Tension'),
    ROW('consonance', 'Music','HARD',  'Agreeable sounds',                  'Resolution'),
    ROW('transposition','Music','HARD','Shifting key',                      'Same intervals'),
    ROW('intonation', 'Music','HARD',  'Pitch accuracy',                    'In tune'),
    ROW('embouchure', 'Music','HARD',  'Mouth position',                    'Wind players'),

    -- SCIENCE (New category - 100 words)
    ROW('atom',       'Science','EASY',  'Smallest unit',                   'Building block'),
    ROW('cell',       'Science','EASY',  'Life building block',             'Has nucleus'),
    ROW('water',      'Science','EASY',  'H2O',                             'Essential for life'),
    ROW('air',        'Science','EASY',  'What we breathe',                 'Mostly nitrogen'),
    ROW('fire',       'Science','EASY',  'Combustion result',               'Hot and bright'),
    ROW('earth',      'Science','EASY',  'Our planet',                      'Third from sun'),
    ROW('sun',        'Science','EASY',  'Our star',                        'Gives light'),
    ROW('moon',       'Science','EASY',  'Earth satellite',                 'Causes tides'),
    ROW('star',       'Science','EASY',  'Ball of gas',                     'Produces light'),
    ROW('planet',     'Science','EASY',  'Orbits a star',                   'Eight in our system'),
    ROW('rock',       'Science','EASY',  'Solid mineral',                   'Makes up earth'),
    ROW('metal',      'Science','EASY',  'Shiny element',                   'Conducts electricity'),
    ROW('plant',      'Science','EASY',  'Photosynthesis',                  'Makes oxygen'),
    ROW('animal',     'Science','EASY',  'Living creature',                 'Kingdom'),
    ROW('bone',       'Science','EASY',  'Skeleton part',                   'Hard tissue'),
    ROW('muscle',     'Science','EASY',  'Body tissue',                     'Makes movement'),
    ROW('brain',      'Science','EASY',  'Thinking organ',                  'In the head'),
    ROW('heart',      'Science','EASY',  'Pumps blood',                     'In the chest'),
    ROW('lung',       'Science','EASY',  'Breathing organ',                 'Takes in oxygen'),
    ROW('blood',      'Science','EASY',  'Red fluid',                       'Carries oxygen'),
    ROW('skin',       'Science','EASY',  'Body covering',                   'Largest organ'),
    ROW('light',      'Science','EASY',  'Electromagnetic',                 'We see with it'),
    ROW('heat',       'Science','EASY',  'Thermal energy',                  'Hot'),
    ROW('sound',      'Science','EASY',  'Vibrations',                      'We hear it'),
    ROW('energy',     'Science','MEDIUM','Ability to work',                 'Cannot be destroyed'),
    ROW('force',      'Science','MEDIUM','Push or pull',                    'Newton'),
    ROW('gravity',    'Science','MEDIUM','Attractive force',                'Pulls things down'),
    ROW('magnet',     'Science','MEDIUM','Attracts iron',                   'North and south'),
    ROW('electric',   'Science','MEDIUM','Charge flow',                     'Powers devices'),
    ROW('wave',       'Science','MEDIUM','Energy transfer',                 'Light and sound'),
    ROW('gas',        'Science','MEDIUM','State of matter',                 'Fills container'),
    ROW('liquid',     'Science','MEDIUM','State of matter',                 'Takes container shape'),
    ROW('solid',      'Science','MEDIUM','State of matter',                 'Fixed shape'),
    ROW('element',    'Science','MEDIUM','Pure substance',                  'Periodic table'),
    ROW('compound',   'Science','MEDIUM','Combined elements',               'Molecules'),
    ROW('molecule',   'Science','MEDIUM','Bonded atoms',                    'Chemical unit'),
    ROW('electron',   'Science','MEDIUM','Negative particle',               'Orbits nucleus'),
    ROW('proton',     'Science','MEDIUM','Positive particle',               'In nucleus'),
    ROW('neutron',    'Science','MEDIUM','Neutral particle',                'In nucleus'),
    ROW('nucleus',    'Science','MEDIUM','Atom center',                     'Dense core'),
    ROW('chemical',   'Science','MEDIUM','Substance',                       'Made of elements'),
    ROW('reaction',   'Science','MEDIUM','Chemical change',                 'Creates new substances'),
    ROW('acid',       'Science','MEDIUM','Low pH',                          'Sour'),
    ROW('base',       'Science','MEDIUM','High pH',                         'Alkaline'),
    ROW('oxygen',     'Science','MEDIUM','Element O',                       'We breathe it'),
    ROW('carbon',     'Science','MEDIUM','Element C',                       'Basis of life'),
    ROW('hydrogen',   'Science','MEDIUM','Lightest element',                'H'),
    ROW('nitrogen',   'Science','MEDIUM','Element N',                       'Most of air'),
    ROW('gene',       'Science','MEDIUM','DNA unit',                        'Heredity'),
    ROW('dna',        'Science','MEDIUM','Genetic code',                    'Double helix'),
    ROW('virus',      'Science','MEDIUM','Infectious agent',                'Needs host'),
    ROW('bacteria',   'Science','MEDIUM','Single-celled',                   'Can be helpful'),
    ROW('protein',    'Science','MEDIUM','Amino acids',                     'Building blocks'),
    ROW('evolution',  'Science','MEDIUM','Species change',                  'Natural selection'),
    ROW('fossil',     'Science','MEDIUM','Ancient remains',                 'In rock'),
    ROW('volcano',    'Science','MEDIUM','Erupts lava',                     'Mountain'),
    ROW('earthquake', 'Science','MEDIUM','Ground shaking',                  'Plate movement'),
    ROW('climate',    'Science','MEDIUM','Long-term weather',               'Changing'),
    ROW('ecosystem',  'Science','HARD',  'Living community',                'Interconnected'),
    ROW('photosynthesis','Science','HARD','Plants make food',               'Using light'),
    ROW('mitochondria','Science','HARD', 'Cell powerhouse',                 'Energy production'),
    ROW('chromosome', 'Science','HARD',  'DNA package',                     'In nucleus'),
    ROW('genome',     'Science','HARD',  'All genetic info',                'Complete set'),
    ROW('enzyme',     'Science','HARD',  'Biological catalyst',             'Speeds reactions'),
    ROW('hormone',    'Science','HARD',  'Chemical messenger',              'Body regulation'),
    ROW('neuron',     'Science','HARD',  'Nerve cell',                      'Transmits signals'),
    ROW('synapse',    'Science','HARD',  'Neural connection',               'Between neurons'),
    ROW('cytoplasm',  'Science','HARD',  'Cell fluid',                      'Inside membrane'),
    ROW('nucleus',    'Science','HARD',  'Cell control center',             'Contains DNA'),
    ROW('plasma',     'Science','HARD',  'Fourth state',                    'Ionized gas'),
    ROW('isotope',    'Science','HARD',  'Atomic variant',                  'Different neutrons'),
    ROW('ion',        'Science','HARD',  'Charged atom',                    'Lost or gained electrons'),
    ROW('catalyst',   'Science','HARD',  'Speeds reaction',                 'Unchanged'),
    ROW('entropy',    'Science','HARD',  'Disorder measure',                'Thermodynamics'),
    ROW('momentum',   'Science','HARD',  'Mass times velocity',             'Conserved'),
    ROW('velocity',   'Science','HARD',  'Speed with direction',            'Vector'),
    ROW('acceleration','Science','HARD', 'Rate of velocity change',         'Force over mass'),
    ROW('friction',   'Science','HARD',  'Resistance force',                'Opposes motion'),
    ROW('inertia',    'Science','HARD',  'Resistance to change',            'First law'),
    ROW('wavelength', 'Science','HARD',  'Wave distance',                   'Peak to peak'),
    ROW('frequency',  'Science','HARD',  'Waves per second',                'Hertz'),
    ROW('amplitude',  'Science','HARD',  'Wave height',                     'Energy'),
    ROW('spectrum',   'Science','HARD',  'Range of waves',                  'Rainbow'),
    ROW('relativity', 'Science','HARD',  'Einstein theory',                 'Space and time'),
    ROW('quantum',    'Science','HARD',  'Smallest unit',                   'Particle physics'),
    ROW('antimatter', 'Science','HARD',  'Opposite matter',                 'Annihilates'),
    ROW('supernova',  'Science','HARD',  'Star explosion',                  'Very bright'),
    ROW('quasar',     'Science','HARD',  'Active galaxy core',              'Distant'),
    ROW('nebula',     'Science','HARD',  'Gas cloud',                       'Star nursery'),
    ROW('pulsar',     'Science','HARD',  'Rotating star',                   'Emits beams'),
    ROW('magnetar',   'Science','HARD',  'Magnetic star',                   'Neutron star'),
    ROW('tectonic',   'Science','HARD',  'Plate movement',                  'Earth''s crust'),
    ROW('geothermal', 'Science','HARD',  'Earth heat',                      'Underground'),
    ROW('biome',      'Science','HARD',  'Large ecosystem',                 'Desert, forest'),
    ROW('symbiosis',  'Science','HARD',  'Species together',                'Mutual benefit'),
    ROW('mutation',   'Science','HARD',  'DNA change',                      'Variation'),
    ROW('allele',     'Science','HARD',  'Gene variant',                    'Inheritance'),
    ROW('phenotype',  'Science','HARD',  'Observable traits',               'Expression'),
    ROW('genotype',   'Science','HARD',  'Genetic makeup',                  'Internal'),
    ROW('osmosis',    'Science','HARD',  'Water movement',                  'Through membrane'),
    ROW('diffusion',  'Science','HARD',  'Particle spreading',              'High to low'),

    -- GEOGRAPHY (New category - 100 words)
    ROW('map',        'Geography','EASY',  'Shows locations',               'Paper or digital'),
    ROW('ocean',      'Geography','EASY',  'Large water body',              'Saltwater'),
    ROW('river',      'Geography','EASY',  'Flowing water',                 'To the sea'),
    ROW('lake',       'Geography','EASY',  'Inland water',                  'Surrounded by land'),
    ROW('mountain',   'Geography','EASY',  'High landform',                 'Has peak'),
    ROW('island',     'Geography','EASY',  'Land in water',                 'Surrounded'),
    ROW('desert',     'Geography','EASY',  'Dry area',                      'Little rain'),
    ROW('forest',     'Geography','EASY',  'Many trees',                    'Woodland'),
    ROW('city',       'Geography','EASY',  'Urban area',                    'Many people'),
    ROW('country',    'Geography','EASY',  'Nation',                        'Has borders'),
    ROW('continent',  'Geography','EASY',  'Large landmass',                'Seven total'),
    ROW('north',      'Geography','EASY',  'Direction',                     'Toward Arctic'),
    ROW('south',      'Geography','EASY',  'Direction',                     'Toward Antarctic'),
    ROW('east',       'Geography','EASY',  'Direction',                     'Sunrise'),
    ROW('west',       'Geography','EASY',  'Direction',                     'Sunset'),
    ROW('beach',      'Geography','EASY',  'Sandy shore',                   'By ocean'),
    ROW('hill',       'Geography','EASY',  'Small elevation',               'Smaller than mountain'),
    ROW('valley',     'Geography','EASY',  'Low area',                      'Between mountains'),
    ROW('coast',      'Geography','EASY',  'Land by sea',                   'Shoreline'),
    ROW('border',     'Geography','EASY',  'Country edge',                  'Dividing line'),
    ROW('capital',    'Geography','EASY',  'Main city',                     'Government seat'),
    ROW('state',      'Geography','EASY',  'Region',                        'Part of country'),
    ROW('pole',       'Geography','MEDIUM','Earth ends',                    'North or South'),
    ROW('equator',    'Geography','MEDIUM','Middle line',                   'Divides hemispheres'),
    ROW('hemisphere', 'Geography','MEDIUM','Half of Earth',                 'North or South'),
    ROW('latitude',   'Geography','MEDIUM','Horizontal lines',              'Distance from equator'),
    ROW('longitude',  'Geography','MEDIUM','Vertical lines',                'Distance from prime meridian'),
    ROW('climate',    'Geography','MEDIUM','Weather patterns',              'Long-term'),
    ROW('tropics',    'Geography','MEDIUM','Near equator',                  'Hot region'),
    ROW('arctic',     'Geography','MEDIUM','North polar',                   'Very cold'),
    ROW('antarctic',  'Geography','MEDIUM','South polar',                   'Coldest continent'),
    ROW('glacier',    'Geography','MEDIUM','Ice mass',                      'Moving slowly'),
    ROW('volcano',    'Geography','MEDIUM','Erupting mountain',             'Lava'),
    ROW('canyon',     'Geography','MEDIUM','Deep valley',                   'Carved by river'),
    ROW('plateau',    'Geography','MEDIUM','Flat highland',                 'Elevated plain'),
    ROW('peninsula',  'Geography','MEDIUM','Land surrounded mostly',        'By water'),
    ROW('bay',        'Geography','MEDIUM','Water inlet',                   'Partially enclosed'),
    ROW('gulf',       'Geography','MEDIUM','Large bay',                     'Deep inlet'),
    ROW('strait',     'Geography','MEDIUM','Narrow water',                  'Connects seas'),
    ROW('delta',      'Geography','MEDIUM','River mouth',                   'Fan-shaped'),
    ROW('reef',       'Geography','MEDIUM','Underwater ridge',              'Coral'),
    ROW('savanna',    'Geography','MEDIUM','Grassland',                     'Tropical'),
    ROW('tundra',     'Geography','MEDIUM','Frozen plain',                  'Arctic'),
    ROW('prairie',    'Geography','MEDIUM','Grassland',                     'North America'),
    ROW('jungle',     'Geography','MEDIUM','Dense forest',                  'Tropical'),
    ROW('rainforest', 'Geography','MEDIUM','Wet forest',                    'High rainfall'),
    ROW('swamp',      'Geography','MEDIUM','Wetland',                       'Waterlogged'),
    ROW('marsh',      'Geography','MEDIUM','Wet grassland',                 'Wetland'),
    ROW('oasis',      'Geography','MEDIUM','Desert water',                  'Fertile spot'),
    ROW('archipelago','Geography','MEDIUM','Island chain',                  'Group of islands'),
    ROW('atoll',      'Geography','MEDIUM','Ring-shaped island',            'Coral'),
    ROW('fjord',      'Geography','MEDIUM','Narrow inlet',                  'Steep cliffs'),
    ROW('cape',       'Geography','MEDIUM','Coastal point',                 'Extends into sea'),
    ROW('isthmus',    'Geography','HARD',  'Narrow land strip',             'Connects landmasses'),
    ROW('estuary',    'Geography','HARD',  'River meets sea',               'Tidal'),
    ROW('lagoon',     'Geography','HARD',  'Shallow water',                 'Separated from sea'),
    ROW('tributary',  'Geography','HARD',  'River branch',                  'Feeds main river'),
    ROW('watershed',  'Geography','HARD',  'Drainage basin',                'Collects water'),
    ROW('aquifer',    'Geography','HARD',  'Underground water',             'Natural storage'),
    ROW('geyser',     'Geography','HARD',  'Hot spring',                    'Erupts water'),
    ROW('crevasse',   'Geography','HARD',  'Glacier crack',                 'Deep fissure'),
    ROW('moraine',    'Geography','HARD',  'Glacial deposit',               'Rocky debris'),
    ROW('escarpment', 'Geography','HARD',  'Steep slope',                   'Cliff'),
    ROW('butte',      'Geography','HARD',  'Isolated hill',                 'Flat-topped'),
    ROW('mesa',       'Geography','HARD',  'Flat-topped hill',              'Larger than butte'),
    ROW('cirque',     'Geography','HARD',  'Bowl-shaped hollow',            'Glacial erosion'),
    ROW('caldera',    'Geography','HARD',  'Volcanic crater',               'Collapsed'),
    ROW('rift',       'Geography','HARD',  'Crack in earth',                'Tectonic'),
    ROW('fault',      'Geography','HARD',  'Rock fracture',                 'Earthquake zone'),
    ROW('pangaea',    'Geography','HARD',  'Supercontinent',                'Ancient landmass'),
    ROW('subduction', 'Geography','HARD',  'Plate movement',                'One under another'),
    ROW('topography', 'Geography','HARD',  'Surface features',              'Terrain'),
    ROW('bathymetry', 'Geography','HARD',  'Ocean floor',                   'Underwater mapping'),
    ROW('permafrost', 'Geography','HARD',  'Frozen ground',                 'Year-round'),
    ROW('taiga',      'Geography','HARD',  'Boreal forest',                 'Northern'),
    ROW('steppe',     'Geography','HARD',  'Dry grassland',                 'Semi-arid'),
    ROW('chaparral',  'Geography','HARD',  'Shrubland',                     'Mediterranean'),
    ROW('mangrove',   'Geography','HARD',  'Coastal trees',                 'Salt-tolerant'),
    ROW('kelp',       'Geography','HARD',  'Seaweed forest',                'Underwater'),
    ROW('karst',      'Geography','HARD',  'Limestone terrain',             'Caves and sinkholes'),
    ROW('sinkhole',   'Geography','HARD',  'Ground collapse',               'Karst feature'),
    ROW('stalactite', 'Geography','HARD',  'Cave formation',                'Hangs down'),
    ROW('stalagmite', 'Geography','HARD',  'Cave formation',                'Grows up'),
    ROW('geomorphology','Geography','HARD','Landform study',                'Surface processes'),
    ROW('lithosphere','Geography','HARD',  'Rocky outer layer',             'Crust and mantle'),
    ROW('hydrosphere','Geography','HARD',  'Water layer',                   'All water'),
    ROW('biosphere',  'Geography','HARD',  'Living zone',                   'Life exists'),
    ROW('atmosphere', 'Geography','HARD',  'Air layer',                     'Surrounds Earth'),
    ROW('troposphere','Geography','HARD',  'Lowest atmosphere',             'Weather'),
    ROW('stratosphere','Geography','HARD', 'Second layer',                  'Ozone'),
    ROW('continental','Geography','HARD',  'Related to land',               'Shelf'),
    ROW('maritime',   'Geography','HARD',  'Related to sea',                'Ocean climate'),
    ROW('orographic', 'Geography','HARD',  'Mountain weather',              'Rain shadow'),
    ROW('monsoon',    'Geography','HARD',  'Seasonal wind',                 'Brings rain'),
    ROW('doldrums',   'Geography','HARD',  'Calm equator zone',             'Low wind'),
    ROW('tradewinds', 'Geography','HARD',  'Consistent winds',              'Tropical'),
    ROW('jetstream',  'Geography','HARD',  'High altitude wind',            'Fast currents'),
    ROW('thalweg',    'Geography','HARD',  'River''s deepest line',         'Channel center'),
    ROW('meridian',   'Geography','HARD',  'Longitude line',                'Prime is zero'),
    ROW('antipode',   'Geography','HARD',  'Opposite point',                'Other side of Earth'),
    ROW('azimuth',    'Geography','HARD',  'Horizontal angle',              'Direction measurement'),

    -- HOUSEHOLD (New category - 100 words)
    ROW('door',       'Household','EASY',  'Entry way',                     'Open and close'),
    ROW('window',     'Household','EASY',  'See outside',                   'Glass opening'),
    ROW('table',      'Household','EASY',  'Flat surface',                  'Put things on'),
    ROW('chair',      'Household','EASY',  'Sitting furniture',             'Has legs'),
    ROW('bed',        'Household','EASY',  'Sleeping furniture',            'Has mattress'),
    ROW('lamp',       'Household','EASY',  'Light source',                  'Plugs in'),
    ROW('clock',      'Household','EASY',  'Tells time',                    'On wall or table'),
    ROW('mirror',     'Household','EASY',  'Shows reflection',              'Glass surface'),
    ROW('towel',      'Household','EASY',  'Drying cloth',                  'In bathroom'),
    ROW('soap',       'Household','EASY',  'Cleaning agent',                'Makes bubbles'),
    ROW('brush',      'Household','EASY',  'Has bristles',                  'For cleaning'),
    ROW('broom',      'Household','EASY',  'Sweeping tool',                 'Long handle'),
    ROW('bucket',     'Household','EASY',  'Container',                     'Holds water'),
    ROW('plate',      'Household','EASY',  'Eating surface',                'Holds food'),
    ROW('cup',        'Household','EASY',  'Drinking vessel',               'Has handle'),
    ROW('fork',       'Household','EASY',  'Eating utensil',                'Has prongs'),
    ROW('spoon',      'Household','EASY',  'Eating utensil',                'Has bowl'),
    ROW('knife',      'Household','EASY',  'Cutting tool',                  'Sharp blade'),
    ROW('pan',        'Household','EASY',  'Cooking vessel',                'Frying'),
    ROW('pot',        'Household','EASY',  'Cooking vessel',                'Boiling'),
    ROW('oven',       'Household','EASY',  'Cooking appliance',             'Bakes food'),
    ROW('refrigerator','Household','EASY', 'Keeps food cold',               'In kitchen'),
    ROW('sink',       'Household','EASY',  'Water basin',                   'For washing'),
    ROW('sofa',       'Household','MEDIUM','Long seat',                     'Living room'),
    ROW('couch',      'Household','MEDIUM','Upholstered seat',              'Comfortable'),
    ROW('pillow',     'Household','MEDIUM','Head cushion',                  'For sleeping'),
    ROW('blanket',    'Household','MEDIUM','Covering cloth',                'Keeps warm'),
    ROW('carpet',     'Household','MEDIUM','Floor covering',                'Soft'),
    ROW('curtain',    'Household','MEDIUM','Window covering',               'Blocks light'),
    ROW('shelf',      'Household','MEDIUM','Storage surface',               'On wall'),
    ROW('drawer',     'Household','MEDIUM','Sliding compartment',           'In furniture'),
    ROW('closet',     'Household','MEDIUM','Storage room',                  'For clothes'),
    ROW('cabinet',    'Household','MEDIUM','Storage furniture',             'Has doors'),
    ROW('dresser',    'Household','MEDIUM','Clothing storage',              'With drawers'),
    ROW('nightstand', 'Household','MEDIUM','Bedside table',                 'Small'),
    ROW('bookshelf',  'Household','MEDIUM','Book storage',                  'Shelves'),
    ROW('desk',       'Household','MEDIUM','Work surface',                  'For writing'),
    ROW('stool',      'Household','MEDIUM','Backless seat',                 'Often at counter'),
    ROW('ottoman',    'Household','MEDIUM','Footrest',                      'Cushioned'),
    ROW('recliner',   'Household','MEDIUM','Leaning chair',                 'Adjustable'),
    ROW('chandelier', 'Household','MEDIUM','Hanging light',                 'Decorative'),
    ROW('vase',       'Household','MEDIUM','Flower container',              'Decorative'),
    ROW('candle',     'Household','MEDIUM','Wax light',                     'Burns'),
    ROW('frame',      'Household','MEDIUM','Picture holder',                'On wall'),
    ROW('rug',        'Household','MEDIUM','Small carpet',                  'Area coverage'),
    ROW('blender',    'Household','MEDIUM','Mixing appliance',              'Makes smoothies'),
    ROW('toaster',    'Household','MEDIUM','Bread appliance',               'Makes toast'),
    ROW('microwave',  'Household','MEDIUM','Heating appliance',             'Quick cooking'),
    ROW('dishwasher', 'Household','MEDIUM','Cleaning appliance',            'For dishes'),
    ROW('washer',     'Household','MEDIUM','Laundry machine',               'Cleans clothes'),
    ROW('dryer',      'Household','MEDIUM','Laundry machine',               'Dries clothes'),
    ROW('vacuum',     'Household','MEDIUM','Cleaning machine',              'Sucks dirt'),
    ROW('iron',       'Household','MEDIUM','Pressing tool',                 'Removes wrinkles'),
    ROW('thermostat', 'Household','MEDIUM','Temperature control',           'Heating cooling'),
    ROW('doorbell',   'Household','MEDIUM','Entry signal',                  'Rings'),
    ROW('mailbox',    'Household','MEDIUM','Letter receptacle',             'Outside'),
    ROW('showerhead', 'Household','MEDIUM','Water fixture',                 'Spray'),
    ROW('faucet',     'Household','MEDIUM','Water tap',                     'Turn on off'),
    ROW('armoire',    'Household','HARD',  'Large wardrobe',                'Freestanding'),
    ROW('credenza',   'Household','HARD',  'Low cabinet',                   'Dining room'),
    ROW('chiffonier', 'Household','HARD',  'Tall narrow dresser',           'Many drawers'),
    ROW('settee',     'Household','HARD',  'Small sofa',                    'Two seats'),
    ROW('chaise',     'Household','HARD',  'Long chair',                    'For reclining'),
    ROW('buffet',     'Household','HARD',  'Dining sideboard',              'Storage'),
    ROW('hutch',      'Household','HARD',  'Display cabinet',               'Glass doors'),
    ROW('armchair',   'Household','HARD',  'Chair with arms',               'Comfortable'),
    ROW('futon',      'Household','HARD',  'Foldable bed',                  'Japanese origin'),
    ROW('divan',      'Household','HARD',  'Backless sofa',                 'Low seating'),
    ROW('hassock',    'Household','HARD',  'Cushioned stool',               'Footrest'),
    ROW('sconce',     'Household','HARD',  'Wall light',                    'Mounted'),
    ROW('torchiere',  'Household','HARD',  'Upward light',                  'Floor lamp'),
    ROW('valance',    'Household','HARD',  'Window topper',                 'Decorative'),
    ROW('duvet',      'Household','HARD',  'Bed cover',                     'Filled'),
    ROW('coverlet',   'Household','HARD',  'Light bedspread',               'Decorative'),
    ROW('bolster',    'Household','HARD',  'Long pillow',                   'Cylindrical'),
    ROW('sham',       'Household','HARD',  'Decorative pillow cover',       'Bedding'),
    ROW('finial',     'Household','HARD',  'Decorative end piece',          'On curtain rod'),
    ROW('escutcheon', 'Household','HARD',  'Door plate',                    'Around keyhole'),
    ROW('newel',      'Household','HARD',  'Stair post',                    'End of railing'),
    ROW('baluster',   'Household','HARD',  'Railing post',                  'Supports handrail'),
    ROW('wainscoting','Household','HARD',  'Wall paneling',                 'Lower half'),
    ROW('cornice',    'Household','HARD',  'Crown molding',                 'Wall ceiling joint'),
    ROW('baseboard',  'Household','HARD',  'Floor trim',                    'Wall floor joint'),
    ROW('mullion',    'Household','HARD',  'Window divider',                'Between panes'),
    ROW('jamb',       'Household','HARD',  'Door frame side',               'Vertical'),
    ROW('lintel',     'Household','HARD',  'Door top beam',                 'Horizontal'),
    ROW('threshold',  'Household','HARD',  'Door bottom',                   'Step over'),
    ROW('transom',    'Household','HARD',  'Window above door',             'For light'),
    ROW('dormer',     'Household','HARD',  'Roof window',                   'Projects out'),
    ROW('gable',      'Household','HARD',  'Roof end wall',                 'Triangular'),
    ROW('eave',       'Household','HARD',  'Roof edge',                     'Overhangs'),
    ROW('soffit',     'Household','HARD',  'Under eave',                    'Enclosed'),
    ROW('fascia',     'Household','HARD',  'Roof edge board',               'Behind gutter'),
    ROW('flashing',   'Household','HARD',  'Roof waterproofing',            'Metal'),
    ROW('joinery',    'Household','HARD',  'Woodwork joints',               'Craftsmanship'),
    ROW('mortise',    'Household','HARD',  'Wood joint hole',               'For tenon'),
    ROW('tenon',      'Household','HARD',  'Wood joint peg',                'Into mortise'),
    ROW('dado',       'Household','HARD',  'Lower wall section',            'Different finish'),
    ROW('frieze',     'Household','HARD',  'Decorative band',               'On wall'),
    ROW('architrave', 'Household','HARD',  'Door window frame',             'Molding')

) AS tmp (original, category, difficulty, hint1, hint2);